source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'StatusBarKit_Example', :exclusive => true do
  pod "StatusBarKit", :path => "../"
end

target 'StatusBarKit_Tests', :exclusive => true do
  pod "StatusBarKit", :path => "../"

  
end
